### ISSUE TITLE
breaks if output of stderr is redirected

### ISSUE THREAD

**Issue by bahbarnett** [liske/needrestart#294] opened 2023-12-13 07:45 UTC
If I run:

```
# output=`needrestart -q -r l -f text `;echo "$?" ; echo "A: $output"
0
A: Pending kernel upgrade
----------------------

Newer kernel available

The currently running kernel version is 6.1.0-13-amd64 which is not the expected kernel version 6.1.0-15-amd64.

Restarting the system to load the new kernel will not be handled automatically, so you should consider rebooting.
```

All is fine.  If I run:

```
# output=`needrestart -q -r l -f text 2>&1 `;echo "$?" ; echo "A: $output"
0
A:
```

all output vanishes.

The above worked fine on 3,.4, yet borks on 3.6.

**Comment by liske** [comment] 2024-04-21 10:03
Running needrestart with stdin, stdout nor stderr being a terminal switches the user interface to `stdio`:

https://github.com/liske/needrestart/blob/2f077c714085a8eb45396da1951b28da181ce277/needrestart#L50

I cannot yet understand what could cause this issue.

**Comment by liske** [comment] 2024-08-09 19:55
It looks like that this might be triggered by debconf. I was not able to reproduce it when needrestart does not use debconf:

```console
# output=`needrestart -q -r l -u NeedRestart::UI::stdio`; echo "$?" ; echo "A: $output"
```

Does this work for you?

**Comment by liske** [comment] 2024-08-10 08:23
I'm closing this issue for now, feel free to reopen it if the problem still exists with the changed UI package.

**Closed by liske** 2024-08-10 08:23 UTC
Labels: bug
