### ISSUE TITLE
Script broken with kernel8.img

### ISSUE THREAD

**Issue by iandstanley** [liske/needrestart#180] opened 2020-05-14 20:05 UTC
With the latest version of Raspbian the Pi foundation have released a 64bit kernel as kernel8.img.

This kernel is an experimental (their words) kernel with 64 bit support for (deleted not interested) However, needrestart sees this as a new kernel and recommends a reboot.

This occurs under **docker-compose** installation and presumably under anything else that needs this package.

the result is that the needrestart script breaks the **sudo apt upgrade** and **sudo apt install package** process resulting in a pop up display after each execution.

This means that ANY automation is broken - no scripting no ansible or any other automation that requires the use of the apt command once another application like docker-compose has been installed

The needrestart Must script misinterprets the kernel String either assuming that kernel8.img Or the full kernel Version string Ending in 8 is an upgrade over the previous version 7L

The last digit (8 or 7L) refers to the architecture arm7 or arm8 and should therefore be truncated before comparing

**Comment by iandstanley** [comment] 2020-06-25 15:30
there is an easy WORKAROUND to this - don't have the interactive dialog as the default - as this will break ALL automated deployments on the PI

The config file line 195 needs to be un-commented to read:
`$nrconf{kernelhints} = -1;
`

the actual fix needs to assess what ARM architecture it is running on  v7l+ or v8+ and handle the kernel version number correctly ie drop the -v[7|8]*$ before comparison

The default use causes too much confusion for Raspberry Pi users who either waste hours of time trying and failing to upgrade from the v7 to the v8 kernel OR who end up with a system that complains that there is an error in the system configuration when there isn't

**Comment by liske** [comment] 2020-06-27 08:12
This is by design and seems to be related to #146 and #155. You can use the [`kernelfilter` setting](https://github.com/liske/needrestart/blob/master/ex/needrestart.conf#L179-L181) to ignore the unused kernel image (requires needrestart 3.5+).

**Comment by liske** [comment] 2020-11-23 21:33
Closing since it seems to be resolved.

**Closed by liske** 2020-11-23 21:33 UTC
Labels: question
