### ISSUE TITLE
needrestart doesn't handle dots in service names

### ISSUE THREAD

**Issue by willpower232** [liske/needrestart#77] opened 2017-09-19 09:23 UTC
I am using needrestart 2.6 (whatever is in the default repository) on Ubuntu 16.04.3 with nginx and php-fpm.

The service for php-fpm is called `php7.0-fpm.service` however needrestart always lists it as `0-fpm.service` and so is unable to restart it.

![image](https://user-images.githubusercontent.com/1619102/30585376-883b30fc-9d24-11e7-9785-4a871a32e8e9.png)

![image](https://user-images.githubusercontent.com/1619102/30585354-72fafd76-9d24-11e7-9519-d7dc7bc7b3a8.png)

I am not sure if php-fpm violates a naming convention or if needrestart needs slightly better service name handling.

**Comment by liske** [comment] 2017-10-01 17:18
This is a duplicate of #19 and has been already fixed in needrestart 2.7.

**Closed by liske** 2017-10-01 17:18 UTC
Labels: bug

**Comment by willpower232** [comment] 2017-10-09 18:12
Thanks for letting me know, I see the 17's are already going with 2.11 so next years servers will be much improved!
