### ISSUE TITLE
NR does not detect deleted file descriptor, while checkrestart does

### ISSUE THREAD

**Issue by odenbach** [liske/needrestart#93] opened 2017-11-21 15:29 UTC
I just updated a bunch of packages on some hosts. On one of the hosts checkrestart claims apache2 to be restarted:

root@dares1[~]# checkrestart -v
Found 11 processes using old versions of upgraded files
(1 distinct program)
Process /usr/lib/apache2/mpm-prefork/apache2 (PID: 1498) 
List of deleted files in use:
	/usr/share/perl5/NeedRestart/UI/Debconf.pm (deleted)
[...]

root@dares1[~]# cd /proc/1498/fd
root@dares1[fd]# ls -l
total 0
lr-x------ 1 root root 64 Nov 21 16:09 0 -> /dev/null
l-wx------ 1 root root 64 Nov 21 16:09 1 -> /dev/null
l-wx------ 1 root root 64 Nov 21 16:09 10 -> /var/log/apache2/other_vhosts_access.log
lrwx------ 1 root root 64 Nov 21 16:09 11 -> anon_inode:[eventpoll]
l-wx------ 1 root root 64 Nov 21 16:09 2 -> /var/log/apache2/error.log
lrwx------ 1 root root 64 Nov 21 16:09 3 -> socket:[9743282]
lr-x------ 1 root root 64 Nov 21 16:09 4 -> /usr/share/perl5/NeedRestart/UI/Debconf.pm (deleted)
lrwx------ 1 root root 64 Nov 21 16:09 5 -> socket:[9743283]
lrwx------ 1 root root 64 Nov 21 16:09 6 -> socket:[9743286]
lrwx------ 1 root root 64 Nov 21 16:09 7 -> socket:[9743287]
lr-x------ 1 root root 64 Nov 21 16:09 8 -> pipe:[9743316]
l-wx------ 1 root root 64 Nov 21 16:09 9 -> pipe:[9743316]

(I actually upgraded the needrestart package which updated the Debconf.pm file mentioned above).

Needrestart does _not_ detect the process as to be restarted.

Is this by design? I only found the directory /proc/<pid>/fd being used in Interp/Java.pm, but nowhere else.

Greetings,

Christopher

**Comment by liske** [comment] 2017-11-26 14:00
This is by design. It looks in `/proc/${PID}/maps` for executable file mappings which are pointing to deleted files.

**Comment by liske** [comment] 2017-12-22 11:09
One more comment: I'm a little bit confused why apache has a open fd to `Debconf.pm`. Which init system do you have? It seems like needrestart fails to close the fd before restarting apache2.

**Comment by odenbach** [comment] 2017-12-22 15:26
That was a Debian wheezy machine, so Sys-V init.

I will look at this after the christmas holidays. Have a good time.

**Comment by liske** [comment] 2017-12-22 16:02
I did guess that since systemctl would delegate the restart to systemd and should not be affected by pending fd.

For some reason the `Debconf.pm` is opened as a fd (this is still valid on Debian stretch)  and it seems to not having the FD_CLOEXEC flag set so it will survive fork-and-exec of perl's `system` function used by needrestart.

**Comment by liske** [comment] 2018-09-02 16:51
Should be fixed since the release of needrestart 3.2 (bugfix for Debian Bug#893152).

**Closed by liske** 2018-09-02 16:51 UTC
Labels: bug
