### ISSUE TITLE
needrestart fails with Can't cd to (unreachable)/srv/www: No such file or directory

### ISSUE THREAD

**Issue by chgarling** [liske/needrestart#177] opened 2020-03-05 10:01 UTC
needrestart fails with Can't cd to (unreachable)/srv/www: No such file or directory on one of our SLES 12.4 systems.

Please find some detail informations here:

# needrestart -v
[main] eval /etc/needrestart/needrestart.conf
[main] needrestart v2.11
[main] running in root mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] detected systemd
[Core] #1115 is a NeedRestart::Interp::Perl
[Perl] #1115: source=/etc/apache2/scripts/apache_filter_log.pl
Can't cd to (unreachable)/srv/www: No such file or directory

# cat /etc/os-release 
NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp4"

# rpm -qa | grep needrestart
needrestart-2.11-22.1.noarch

Just let me know, if you need further information to investigate in this issue.

**Comment by liske** [comment] 2020-03-07 21:40
This looks like a duplicate of #99.

**Closed** 2020-03-21 20:51 UTC
