### ISSUE TITLE
atop detected as cron

### ISSUE THREAD

**Issue by razvanphp** [liske/needrestart#40] opened 2016-09-28 20:15 UTC
Hello,

There seems to be a bug in the 2.7 version, we use debian-jessie package, sometimes we can't get rid of `cron` for `needrestart`, so here are 2 consecutive runs with answer `Y`

```
user@server:~$ sudo needrestart -v
[main] eval /etc/needrestart/needrestart.conf
[main] running in root-mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] detected systemd
[Core] #34090 is a NeedRestart::Interp::Python
[Core] #34098 is a NeedRestart::Interp::Ruby
[Core] #38205 is a NeedRestart::Interp::Python
[Core] #38372 is a NeedRestart::Interp::Python
[Core] #38621 is a NeedRestart::Interp::Python
[main] #123727 uses deleted /lib/x86_64-linux-gnu/libdl-2.19.so
[main] #123727 is not a child
[main] #123727 exe => /usr/bin/atop
[main] #123727 is cron.service
[Kernel] Linux: kernel release 4.6.0-0.bpo.1-amd64, kernel version #1 SMP Debian 4.6.4-1~bpo8+1 (2016-08-11)
Failed to load NeedRestart::Kernel::kFreeBSD: [Kernel/kFreeBSD] Not running on GNU/kFreeBSD!
[Kernel/Linux] /boot/vmlinuz-4.6.0-0.bpo.1-amd64 => 4.6.0-0.bpo.1-amd64 (debian-kernel@lists.debian.org) #1 SMP Debian 4.6.4-1~bpo8+1 (2016-08-11) [4.6.0-0.bpo.1-amd64]*
[Kernel/Linux] Expected linux version: 4.6.0-0.bpo.1-amd64
Running kernel seems to be up-to-date.
Restarting services...
Services to be restarted:
Restart «cron.service»? [Ynas?] y
 systemctl restart cron.service
No containers need to be restarted.
No user sessions are running outdated binaries.
user@server:~$ sudo needrestart -v
[main] eval /etc/needrestart/needrestart.conf
[main] running in root-mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] detected systemd
[Core] #34090 is a NeedRestart::Interp::Python
[Core] #34098 is a NeedRestart::Interp::Ruby
[Core] #38205 is a NeedRestart::Interp::Python
[Core] #38372 is a NeedRestart::Interp::Python
[Core] #38621 is a NeedRestart::Interp::Python
[main] #123727 uses deleted /lib/x86_64-linux-gnu/libdl-2.19.so
[main] #123727 is not a child
[main] #123727 exe => /usr/bin/atop
[main] #123727 is cron.service
[Kernel] Linux: kernel release 4.6.0-0.bpo.1-amd64, kernel version #1 SMP Debian 4.6.4-1~bpo8+1 (2016-08-11)
Failed to load NeedRestart::Kernel::kFreeBSD: [Kernel/kFreeBSD] Not running on GNU/kFreeBSD!
[Kernel/Linux] /boot/vmlinuz-4.6.0-0.bpo.1-amd64 => 4.6.0-0.bpo.1-amd64 (debian-kernel@lists.debian.org) #1 SMP Debian 4.6.4-1~bpo8+1 (2016-08-11) [4.6.0-0.bpo.1-amd64]*
[Kernel/Linux] Expected linux version: 4.6.0-0.bpo.1-amd64
Running kernel seems to be up-to-date.
Restarting services...
Services to be restarted:
Restart «cron.service»? [Ynas?] y
 systemctl restart cron.service
No containers need to be restarted.
No user sessions are running outdated binaries.
user@server:~$ ps aux |grep 123727
user  36999  0.0  0.0  14212  2540 pts/0    S+   22:06   0:00 grep 123727
root     123727  0.0  0.0  25068 12788 ?        S<L  00:00   0:03 /usr/bin/atop -a -w /var/log/atop/atop_20160928 600
user@server:~$ sudo systemctl status atop.service
● atop.service - LSB: Monitor for system resources and process activity
   Loaded: loaded (/etc/init.d/atop)
   Active: active (exited) since Mi 2016-09-07 05:36:37 CEST; 3 weeks 0 days ago

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
user@server:~$ sudo systemctl restart atop.service
user@server:~$ sudo systemctl status atop.service
● atop.service - LSB: Monitor for system resources and process activity
   Loaded: loaded (/etc/init.d/atop)
   Active: active (running) since Mi 2016-09-28 22:08:40 CEST; 1s ago
  Process: 37576 ExecStop=/etc/init.d/atop stop (code=exited, status=0/SUCCESS)
  Process: 37584 ExecStart=/etc/init.d/atop start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/atop.service
           └─37592 /usr/bin/atop -a -w /var/log/atop/atop_20160928 600

Sep 28 22:08:40 ay-p-job2 systemd[1]: Started LSB: Monitor for system resources and process activity.
user@server:~$ ps aux |grep 123727
user  37620  0.0  0.0  14212  2524 pts/0    S+   22:08   0:00 grep 123727
user@server:~$ sudo needrestart -v
[main] eval /etc/needrestart/needrestart.conf
[main] running in root-mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] detected systemd
[Core] #34090 is a NeedRestart::Interp::Python
[Core] #34098 is a NeedRestart::Interp::Ruby
[Core] #38205 is a NeedRestart::Interp::Python
[Core] #38372 is a NeedRestart::Interp::Python
[Core] #38621 is a NeedRestart::Interp::Python
[Kernel] Linux: kernel release 4.6.0-0.bpo.1-amd64, kernel version #1 SMP Debian 4.6.4-1~bpo8+1 (2016-08-11)
Failed to load NeedRestart::Kernel::kFreeBSD: [Kernel/kFreeBSD] Not running on GNU/kFreeBSD!
[Kernel/Linux] /boot/vmlinuz-4.6.0-0.bpo.1-amd64 => 4.6.0-0.bpo.1-amd64 (debian-kernel@lists.debian.org) #1 SMP Debian 4.6.4-1~bpo8+1 (2016-08-11) [4.6.0-0.bpo.1-amd64]*
[Kernel/Linux] Expected linux version: 4.6.0-0.bpo.1-amd64
Running kernel seems to be up-to-date.
No services need to be restarted.
No containers need to be restarted.
No user sessions are running outdated binaries.
user@server:~$
```

It is true that atop was running as a zombie, out of systemd control, but still, it has nothing to do with cron.

Thank you!

**Comment by liske** [comment] 2016-10-31 17:15
Hi,

could you please provide the content of `/proc/$PID/cgroup` of the *atop* process? I assume it is within cron's *cgroup*... this would explain why *needrestart* suggests to restart *cron.service*...

TIA,
Thomas

**Comment by liske** [comment] 2017-12-22 11:16
Since missing any feedback I'm going to close this issue. Feel free to reopen it if you were able to reproduce it with a recent needrestart version (2.11+).

**Closed by liske** 2017-12-22 11:16 UTC
Labels: bug, moreinfo
